### PR TITLE
#11 Raise error and reference Mesquite on presence of CHARLABELS/STAT…

### PR DESCRIPTION
**Pull request by kleintom**
…ELABELS

The idea here being to give users a more detailed error message in this case, along with how they might fix the error. We could still leave the issue open if you'd take a pr to actually implement those blocks someday.

### CODE REVIEW

**Comment by mjy** [comment]
@kleintom I merged the other PRs, there is a conflict here, would you mind double checking that it's a simple resolve, or does that check line have to move to the top?

**Comment by mjy** [comment]
@kleintom A ping on this one.  If you have time to check the conflict then I'll fire off a new release?

**Comment by kleintom** [comment]
Merged.

> I'll fire off a new release

You're brave :-)

**Comment by mjy** [comment]
> You're brave :-)

This isn't nuclear reactors, and it's seriously unlikely anyone but TW is using it, we're safe I think  :)

**Pull request merged**
