### PR TITLE
Convert to bundler and require Ruby >= 3.3.0

### PR DESCRIPTION
**Pull request by kleintom**
Some notes:

* No changes were required to run with Ruby 3.3 as far as I can tell
* (As I'm sure you're aware,) default bundle uses the following for the files assignment in gemspec rather than listing out individual files:
```rb
spec.files = Dir.chdir(__dir__) do
  `git ls-files -z`.split("\x0").reject do |f|
    (File.expand_path(f) == __FILE__) ||
      f.start_with?(*%w[bin/ test/ spec/ features/ .git appveyor Gemfile])
  end
end
```
For now I've left it as it was - do you have a preference there?

* My brief impression iirc was that `ruby-debug` isn't active anymore? When I tried to install it I think it said it couldn't find any available required `ruby-debug-base`. For now it's commented out, if that's something I should look into more please let me know.

* My impression was that the `spicycode-rcov` currently referenced in rake isn't active anymore; do you want to swtich to simplecov or something else?

* There was a failing test that's now `omit`ed because it required a file that didn't exist.
*  There's currently one failing test - it expects a size to be 100 but it's actually 10 - another test looked like it expected 10 for the same value and was passing, so maybe 10 is right but I'm not sure yet.
* As far as I can tell everything else is working, but please check me (of course) since I'm new to this - all of the following seem to work:
  *  `bundle install`
  * `bin/setup`
  * `bin/console`
  * `rake test`
  * `rake rdoc`
  * `rake build`
  * `gem install pkg/nexus_parser-1.4.1.gem`
  * trying out the gem with:
    * irb
    * require 'nexus_parser'
    * nf = File.read('test/MX_test_03.nex')
    * parse_nexus_file(nf).codings.size

### CODE REVIEW

**Comment by mjy** [comment]
Thanks!

Let's update bundle/Gemfile to follow pattern in TW.

> My brief impression iirc was that ruby-debug isn't active anymore?

Could very well be, pry might be an alternative, I'm a old-school 'byebug' coder.

`simplecov` is fine as a start. Might not even need that.

**Comment by mjy** [comment]
@kleintom just a note that a more active Gem (maybe not without it's own issues) that I maintain is `sqed`, found in SFG org.  Unifying to patterns there may help in general.

**Comment by kleintom** [comment]
> Let's update bundle/Gemfile to follow pattern in TW.

Do you mean move the dependencies from the gemspec to the gemfile? I've been a little confused around that in general - do you wind up needing to put dependencies in both places? Development stuff I can see just being in the gemfile, but if your gem relies on some version of a non-development gem then doesn't that have to be in the gemspec? Would you put that dependency only in the gemspec then (and include it in the gemfile via the `gemspec` line)?

Or if you put a `ruby` dependency in the gemfile should that also be in the gemspec (as `required_ruby_version`, which doesn't support ~>), and then you'd have to remember to update it in both places? (Just to be clear, I don't mean to question your judgement on this, just trying to sort out how the gemfile and gemspec interact in these cases - thanks!)

**Comment by mjy** [comment]
Sorry for the confusion, was scrambling out the door :(.  We *don't* want to follow the Gem setup in TW, Gem repos are setup a little different!   We want the gem requirements spelled out like [sqed.gemspec](https://github.com/SpeciesFileGroup/sqed/blob/main/sqed.gemspec).  Gem repos are a little different in this regard.

**Comment by mjy** [comment]
@kleintom the value `100` is correct.

**Comment by mjy** [comment]
Fixed the expectation, I suspect `size` changed meanings or was broken.

**Pull request merged**
